export const zaifPairs = [
  'cszaif_zaif',
  'csbtc_btc',
  'btc_jpy',
  'zaif_btc',
  'bch_jpy',
  'cscmseth_erc20.cms',
  'erc20.cms_jpy',
  'cicc_btc',
  'ncxc_jpy',
  'cscmsxem_mosaic.cms',
  'fscc_btc',
  'cseth_eth',
  'xcp_jpy',
  'mona_btc',
  'ncxc_btc',
  'mosaic.cms_btc',
  'xem_btc',
  'cicc_jpy',
  'csxem_xem',
  'eth_jpy',
  'mona_jpy',
  'bch_btc',
  'xcp_btc',
  'fscc_jpy',
  'eth_btc',
  'mosaic.cms_jpy',
  'jpyz_jpy',
  'zaif_jpy',
  'xem_jpy',
  'erc20.cms_btc',
] as const

export const zaifOrderBookPairs = [
  'bch_btc',
  'bch_jpy',
  'btc_jpy',
  'cicc_btc',
  'cicc_jpy',
  'erc20.cms_btc',
  'erc20.cms_jpy',
  'eth_btc',
  'eth_jpy',
  'fscc_btc',
  'fscc_jpy',
  'jpyz_jpy',
  'mona_btc',
  'mona_jpy',
  'mosaic.cms_btc',
  'mosaic.cms_jpy',
  'ncxc_btc',
  'ncxc_jpy',
  'xcp_btc',
  'xcp_jpy',
  'xem_btc',
  'xem_jpy',
  'zaif_btc',
  'zaif_jpy',
] as const

export type ZaifPairs = typeof zaifPairs[number]
export type ZaifOrderBookPairs = typeof zaifOrderBookPairs[number]
