name: Deploy frontend

on:
  push:
    branches:
      - main

    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-release.yml'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn && yarn lerna run --scope frontend build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_COINS_WATCH }}'
          channelId: live
          projectId: coins-watch
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
